language: java
sudo: false
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
 - openjdk6
 - openjdk7
 - openjdk8
env:
  matrix:
  - TERM=dumb
install:
  - export JAVA_HOME_TEMP=$JAVA_HOME
  - jdk_switcher use openjdk8
  - git clone https://github.com/stagemonitor/stagemonitor.git .stagemonitor
  - pushd .stagemonitor
  - git --no-pager log -n 1 --pretty=oneline
  - ./gradlew compileJava installIntegrationSnapshot
  - popd
  - ./gradlew clean # download gradle and plugins with java 8 due to https://github.com/gradle/gradle/issues/2421
  - export JAVA_HOME=$JAVA_HOME_TEMP
  - echo $JAVA_HOME
  - java -version
script:
  - ./gradlew test
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - .downloads
