language: java
sudo: false
dist: precise
jdk:
 - openjdk6
 - oraclejdk7
 - openjdk7
 - oraclejdk8
env:
  matrix:
  - TERM=dumb
install:
  - export JAVA_HOME_TEMP=$JAVA_HOME
  - jdk_switcher use oraclejdk8
  - git clone https://github.com/stagemonitor/stagemonitor.git .stagemonitor
  - pushd .stagemonitor
  - git --no-pager log -n 1 --pretty=oneline
  - ./gradlew compileJava installIntegrationSnapshot
  - popd
  - export JAVA_HOME=$JAVA_HOME_TEMP
  - echo $JAVA_HOME
  - java -version
script:
  - ./gradlew test
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - .downloads
